.TH X12PP 1
.SH NAME
x12pp \- pretty printer for X12 EDI files
.SH SYNOPSIS
.B x12pp
[\fIOPTIONS\fP]... [INPUT] -o OUTPUT
.P
cat [...] |
.B x12pp
| head
.SH DESCRIPTION
.I x12pp
is a filter that pretty-prints X12 files passed through it.
.P
"Pretty printing" in this case means automatically detecting the segment
terminator from the ISA header and then splitting the input data into
one line per segment.
.TP
.B -h, --help
print a brief usage message
.TP
.B -V, --version
print version information
.TP
.B -o, --output
specify the output file; STDOUT if omitted
.TP
.B -u, --uglify
instead of adding post-segment newlines, strip them out
.
.SH AUTHOR
Mike Clarke <mike@lambdafunctions.com>
.SH HOME
https://github.com/clarkema/x12pp
