[package]
name = "x12pp"
version = "0.1.0"
authors = ["Mike Clarke <mike@lambdafunctions.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
memchr = "2.2.0"

[dependencies.clap]
version = "2.33.0"
default-features = false
features = ["yaml", "wrap_help"]
